# Generated by Django 3.2.7 on 2021-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_alter_expenseinfo_user_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
