# Generated by Django 4.0.1 on 2022-02-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
