# Generated by Django 4.0.1 on 2022-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
